Repository marolmmar1/decide-part-camaron-3, pull requests merged in 2023-11, with the labels that each got.

#31 feature_voting_yes_no:
  decide/voting/models.py
  decide/voting/templates/createQuestion.html
  decide/voting/templates/questions.html
  decide/voting/views.py
Labels: enhancement

#48 Feature voting yes no
  decide/voting/migrations/0008_alter_question_third_option.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: testing

#51 Feature voting hierarchy. Closes #17 #18 #27.
  decide/booth/templates/booth/booth.html
  decide/census/migrations/0006_alter_census_role.py
  decide/census/models.py
  decide/census/tests.py
  decide/census/views.py
  decide/voting/migrations/0008_merge_20231126_1259.py
  decide/voting/migrations/0009_alter_question_third_option.py
  decide/voting/migrations/0010_merge_20231126_1309.py
  decide/voting/tests.py
  decide/voting/views.py
Labels: enhancement, testing

#54 Continuous integration implemented
  decide/authentication/test_selenium.py
Labels: bug, enhancement
